### ISSUE TITLE
what's libicgnn??

### ISSUE THREAD

**Issue by 980380446** [griegler/primal-dual-networks#3]
what's libicgnn??where to download??

**Comment by 980380446** [comment]
just solved it

**Comment by 980380446** [comment]
should i make install?

**Comment by griegler** [comment]
libicgnnn is in the common directory. You just need to build it via the cmake and make toolchain. Where you put the binaries does not really matter, just make sure you can find them in the lua scripts.

**Comment by 980380446** [comment]
always build failed,no file doc and readme.md ,so i noted these two,and then build it,but i still can't run the code,it says module './build/libicgnn' not found,could you give me some hints,thanks for your time!!

**Comment by griegler** [comment]
Try to move to the libicgnn director and then 
```
mkdir build
cd build
cmake ..
make
```

**Comment by 980380446** [comment]
i follow you instruction,but i still got this error:
/../common/icgnn/init.lua:33: module './build/libicgnn' not found:
	no field package.preload['./build/libicgnn']

after make should i make install?
so sorry for disturbing you, i am newer of lua language.

**Comment by griegler** [comment]
I do not have enough details, but given that the compilation succeeded, you might have to adjust some paths. You could try to adjust them [here](https://github.com/griegler/primal-dual-networks/blob/master/dsr/method/settings.lua#L36), or [here](https://github.com/griegler/primal-dual-networks/blob/master/common/icgnn/init.lua).

**Comment by 980380446** [comment]
thank you for your patience

**Comment by 980380446** [comment]
sorry to interrupt you again.the python file data2patches.py which generate data patches,why there's not a setting for 256*256?

**Comment by 980380446** [comment]
i met this problem:
 IcgResample.lua:57: attempt to index field 'icgnn' (a nil value)
do you know how to solve it?

**Comment by griegler** [comment]
It sounds that `icgnn` is not correctly included in the project. Maybe recheck the paths mentioned in the answer above.

**Comment by 980380446** [comment]
![tim 20180817172259](https://user-images.githubusercontent.com/17487439/44258803-6d4b6900-a242-11e8-8747-c44781600cb5.png)
I print icgnn, the picture above is what I get. So it's not the path problem, but I don't know why the funcitons started with icg is different from others. Could you tell me your experient environment  such as which version of linux you are using, which version of cuda ...
thank you again.
